<?php


namespace APIHandlers;

require_once 'APIHandler.php';

use APIHandlers\APIHandler;

class AuthHandler extends APIHandler {

    public function handleGet($parts, $body) {
        if ($parts[2] === "status") {
            session_start();
            if (isset($_SESSION['loggedin'])) {
                if ($_SESSION['loggedin'] === true) {
                    echo json_encode(array(
                        "data" => array(
                            array(
                                "loggedin" => true
                            )
                        )
                    ));
                    return;
                }
            }
            echo json_encode(array(
                "data" => array(
                    array(
                        "loggedin" => false
                    )
                )
            ));
            return;
        }
    }

    public function handlePost($parts, $body) {
        if ($parts[2] === "login") {
            $data = json_decode($body, true)['data'][0];
            if ($data) {
                $file = file_get_contents(__DIR__ . "/../../data/data.json");
                $credentials = json_decode($file, true)['user'];
                if ($data['username'] === $credentials['username']) {
                    if (password_verify($data['password'], $credentials['password'])) {
                        session_start();
                        $_SESSION['loggedin'] = true;
                        echo json_encode(array(
                            "data" => array(
                                array(
                                    "status" => "success"
                                )
                            )
                        ));
                        return;
                    }
                }
                echo json_encode(array(
                    "data" => array(
                        array(
                            "status" => "error",
                            "error" => "Wrong credentials"
                        )
                    )
                ));
                return;
            }
            echo json_encode(array(
                "data" => array(
                    array(
                        "status" => "error",
                        "error" => "Malformed request"
                    )
                )
            ));
            return;
        } elseif ($parts[2] === "logout") {
            session_start();
            session_destroy();
            if (!isset($_SESSION['loggedin'])) {
                echo json_encode(array(
                    "data" => array(
                        array(
                            "status" => "success"
                        )
                    )
                ));
                return;
            } else {
                echo json_encode(array(
                    "data" => array(
                        array(
                            "status" => "error",
                        )
                    )
                ));
                return;
            }
        }
    }

    public function handlePut($parts, $body) {
        parent::handlePut($parts, $body); // TODO: Change the autogenerated stub
    }

    public function handleDelete($parts, $body) {
        parent::handleDelete($parts, $body); // TODO: Change the autogenerated stub
    }

}