<?php


namespace APIHandlers;

use Objects\Link;

require_once 'APIHandler.php';
require_once __DIR__.'/../objects/Link.php';
require_once __DIR__.'/../objects/Statistics.php';

class LinkHandler extends APIHandler {

    public function handle($parts) {
        session_start();
        if (!isset($_SESSION['loggedin'])) {
            echo json_encode(array(
                "data" => array(array(
                    "status" => "error",
                    "error" => "Session invalid"
                ))
            ));
            exit();
        }
        parent::handle($parts);
    }

    public function handleGet($parts, $body) {
        if (isset($parts[2])) {
            // do stuff
        } else {
            print json_encode(array(
                "data" =>  Link::getAll()
            ));
        }
    }

    public function handlePost($parts, $body) {
        parent::handlePost($parts, $body); // TODO: Change the autogenerated stub
    }

    public function handlePut($parts, $body) {
        parent::handlePut($parts, $body); // TODO: Change the autogenerated stub
    }

    public function handleDelete($parts, $body) {
        parent::handleDelete($parts, $body); // TODO: Change the autogenerated stub
    }

}